function summary = run_aerialmanipulator_acceptance_suite()
%RUN_AERIALMANIPULATOR_ACCEPTANCE_SUITE Run the validated acceptance cases.

scenarios = {
    struct('label', 'mode1_nominal', ...
        'input', struct('mode', 1, 'arm_angle_max', 1.0), ...
        'sim', struct(), ...
        'expected_field', 'mode1_pass')
    struct('label', 'mode1_small_amp', ...
        'input', struct('mode', 1, 'arm_angle_max', 0.6), ...
        'sim', struct(), ...
        'expected_field', 'mode1_pass')
    struct('label', 'mode2_nominal', ...
        'input', struct('mode', 2, 'T', 20, 'pos_target', [0.2; 0.2; 5]), ...
        'sim', struct(), ...
        'expected_field', 'mode2_pass')
    struct('label', 'mode2_slowed', ...
        'input', struct('mode', 2, 'T', 30, 'pos_target', [0.2; 0.2; 5]), ...
        'sim', struct('stop_time', 30), ...
        'expected_field', 'mode2_pass')
    };

summary = struct();
summary.results = cell(numel(scenarios), 1);

for i = 1:numel(scenarios)
    cfg = struct( ...
        'output', struct('label', scenarios{i}.label), ...
        'input', scenarios{i}.input);

    if ~isempty(fieldnames(scenarios{i}.sim))
        cfg.sim = scenarios{i}.sim;
    end

    result = run_aerialmanipulator_experiment(cfg);
    result.accepted = isfield(result.metrics, scenarios{i}.expected_field) && ...
        result.metrics.(scenarios{i}.expected_field);
    summary.results{i} = result;
end

