function summary = run_aerialmanipulator_tuning()
%RUN_AERIALMANIPULATOR_TUNING Search a moderate empirical-noise controller set.

measurement = struct( ...
    'model', 'empirical', ...
    'quad_delay_steps', 1, ...
    'arm_delay_steps', 0, ...
    'position_noise_std', 0.0013, ...
    'velocity_noise_std', 0.0032, ...
    'attitude_noise_std', 0.0007, ...
    'omega_noise_std', 0.0022, ...
    'hv_noise_std', 0.0035, ...
    'arm_position_noise_std', 0.0032, ...
    'arm_velocity_noise_std', 0.0090, ...
    'arm_acceleration_noise_std', 0.0130, ...
    'end_effector_position_noise_std', 0.0012, ...
    'end_effector_velocity_noise_std', 0.0035);

baseline = struct( ...
    'name', 'baseline', ...
    'system_params', struct(), ...
    'arm_params', struct(), ...
    'position_limits', struct(), ...
    'attitude_limits', struct());

candidates = {
    struct( ...
        'name', 'final_default', ...
        'system_params', struct( ...
            'Omega_p', diag([1.65, 1.65, 16.5]), ...
            'K_v', diag([6.2, 6.2, 16.5]), ...
            'w_p', [3.8, 3.4, 3.0], ...
            'w_o', [4.8, 6.2, 6.2]), ...
        'arm_params', struct( ...
            'K_p', diag([11, 13, 11]), ...
            'K_d', diag([1.1, 1.4, 1.1]), ...
            'K_i', diag([7, 6, 7])), ...
        'position_limits', struct( ...
            'max_lateral_force_ratio', 0.38, ...
            'integral_limit', [0.30; 0.30; 0.50], ...
            'integral_feedback_gain', [0.0; 0.0; 1.60]), ...
        'attitude_limits', struct('tau_max', 22))
    struct( ...
        'name', 'candidate_1', ...
        'system_params', struct( ...
            'K_v', diag([5.8, 5.8, 8.9]), ...
            'w_p', [3.6, 3.2, 2.9], ...
            'w_o', [4.5, 6.0, 6.0]), ...
        'arm_params', struct( ...
            'K_p', diag([10, 12, 10]), ...
            'K_d', diag([1.0, 1.3, 1.0]), ...
            'K_i', diag([8, 7, 8])), ...
        'position_limits', struct('max_lateral_force_ratio', 0.35), ...
        'attitude_limits', struct('tau_max', 20))
    struct( ...
        'name', 'candidate_2', ...
        'system_params', struct( ...
            'K_v', diag([6.2, 6.2, 9.2]), ...
            'w_p', [3.8, 3.4, 3.0], ...
            'w_o', [4.8, 6.2, 6.2]), ...
        'arm_params', struct( ...
            'K_p', diag([11, 13, 11]), ...
            'K_d', diag([1.1, 1.4, 1.1]), ...
            'K_i', diag([7, 6, 7])), ...
        'position_limits', struct('max_lateral_force_ratio', 0.38), ...
        'attitude_limits', struct('tau_max', 22))
    struct( ...
        'name', 'candidate_3', ...
        'system_params', struct( ...
            'K_v', diag([6.5, 6.5, 9.4]), ...
            'Omega_q', diag([0.55, 1.6, 1.6]), ...
            'K_omega', diag([0.7, 1.8, 1.7]), ...
            'w_p', [4.0, 3.6, 3.1], ...
            'w_o', [5.0, 6.5, 6.5]), ...
        'arm_params', struct( ...
            'K_p', diag([12, 14, 12]), ...
            'K_d', diag([1.2, 1.5, 1.2]), ...
            'K_i', diag([6, 5, 6])), ...
        'position_limits', struct('max_lateral_force_ratio', 0.40), ...
        'attitude_limits', struct('tau_max', 24))
    struct( ...
        'name', 'candidate_4', ...
        'system_params', struct( ...
            'K_v', diag([5.5, 5.5, 8.7]), ...
            'w_p', [3.4, 3.0, 2.8], ...
            'w_o', [4.2, 5.8, 5.8]), ...
        'arm_params', struct( ...
            'K_p', diag([9, 11, 9]), ...
            'K_d', diag([0.95, 1.2, 0.95]), ...
            'K_i', diag([8, 7, 8])), ...
        'position_limits', struct('max_lateral_force_ratio', 0.35), ...
        'attitude_limits', struct('tau_max', 18))
    };

all_cases = [{baseline}; candidates(:)];
summary = struct();
summary.measurement = measurement;
summary.results = cell(numel(all_cases), 1);

best_score = inf;
best_idx = 1;

for i = 1:numel(all_cases)
    candidate = all_cases{i};
    mode1 = run_case(candidate, measurement, 1, sprintf('%s_mode1', candidate.name));
    mode2 = run_case(candidate, measurement, 2, sprintf('%s_mode2', candidate.name));

    combined = struct();
    combined.name = candidate.name;
    combined.mode1 = mode1.metrics;
    combined.mode2 = mode2.metrics;
    combined.mode1_file = get_output_file(mode1);
    combined.mode2_file = get_output_file(mode2);
    combined.score = candidate_score(mode1.metrics, mode2.metrics);
    combined.position_pass = all(mode1.metrics.position_axis_max < 0.05) && ...
        all(mode2.metrics.position_axis_max < 0.05);
    combined.arm_pass = all(mode1.metrics.arm_axis_max < 0.10) && ...
        all(mode2.metrics.arm_axis_max < 0.10);
    combined.all_pass = combined.position_pass && combined.arm_pass && ...
        ~mode1.metrics.is_divergent && ~mode2.metrics.is_divergent;

    summary.results{i} = combined;

    if combined.score < best_score
        best_score = combined.score;
        best_idx = i;
    end
end

summary.best = summary.results{best_idx};

function result = run_case(candidate, measurement, mode, label)
cfg = struct();
cfg.input = struct('mode', mode);
cfg.output = struct('label', label, 'save_results', true);
cfg.measurement = measurement;
cfg.controller = struct( ...
    'system_params', candidate.system_params, ...
    'arm_params', candidate.arm_params, ...
    'position_limits', candidate.position_limits, ...
    'attitude_limits', candidate.attitude_limits);

if mode == 2
    cfg.input.T = 20;
    cfg.input.pos_target = [0.2; 0.2; 5];
end

result = run_aerialmanipulator_experiment(cfg);

function score = candidate_score(mode1_metrics, mode2_metrics)
score = 0;
score = score + 10 * sum(mode1_metrics.position_axis_max) + 10 * sum(mode2_metrics.position_axis_max);
score = score + sum(mode1_metrics.arm_axis_max) + sum(mode2_metrics.arm_axis_max);

if mode1_metrics.is_divergent
    score = score + 1e6;
end
if mode2_metrics.is_divergent
    score = score + 1e6;
end

function output_file = get_output_file(result)
output_file = '';
if isfield(result, 'output_file')
    output_file = result.output_file;
end

